/* const code = [
    {
        img: "https://i.ibb.co/gT4W7Xr/web-icon.png",
        name: "Web Development",
    },
    {
        img: "https://i.ibb.co/ZYJz5j5/gd-icon.png",
        name: "Graphics Design",
    },
    {
        img: "https://i.ibb.co/9Hmp2BC/video-icon.png",
        name: "Degital Marketing",
    },
    {
        img: "https://i.ibb.co/1M7VbQY/ca-icon.png",
        name: "Programming Languages",
    },
] */

/* const code = [
    {
        img: "https://i.ibb.co/9ymn2ft/2201164-831a.jpg",
        title: "JavaScript Basics for Beginners",
        instructor: "Mosh Hamedani",
        avg: 4.5,
        rating: "14,022",
        price: 13.99,
    },
    {
        img: "https://i.ibb.co/9ymn2ft/2201164-831a.jpg",
        title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
        instructor: "Maximilian Schwarzmuller ",
        avg: 4.7,
        rating: "126,714",
        price: 16.99,
    },
    {
        img: "https://i.ibb.co/GFZqpk9/1638522-fbdf.jpg",
        title: "The Complete Node.JS Developer Course",
        instructor: "Brad Traversy",
        avg: 4.6,
        rating: "60,774",
        price: 14.99,
    },
    {
        img: "https://i.ibb.co/fr1ZcPv/405282-27d2-3.jpg",
        title: "PHP for Begenners",
        instructor: "Edwin Diaz",
        avg: 4.4,
        rating: "20,406",
        price: 13.99,
    },
    {
        img: "https://i.ibb.co/Mh26zNw/1643044-e281.jpg",
        title: "Graphics Design Masterclass",
        instructor: "Lindsay Marsh",
        avg: 4.0,
        rating: "35,022",
        price: 10.99,
    },
    {
        img: "https://i.ibb.co/tbRcB41/573984-ce2a-3.jpg",
        title: "Social Media Marketing MASTERY",
        instructor: "Course Envy",
        avg: 4.8,
        rating: "10,022",
        price: 12.99,
    },
    {
        img: "https://i.ibb.co/g9ggM6V/629302-8a2d-2.jpg",
        title: "Learn Python Programming Masterclass",
        instructor: "Tim Buchalka",
        avg: 4.5,
        rating: "19,022",
        price: 16.99,
    },
    {
        img: "https://i.ibb.co/7t9n0xG/1576854-9aeb-2.jpg",
        title: "Introduction to programming: C/C++",
        instructor: "Abdul Bari",
        avg: 3.9,
        rating: "15,022",
        price: 11.99,
    },
    {
        img: "https://i.ibb.co/bgMJvF1/850426-5596-4.jpg",
        title: "Photoshop 2021 Masterclass",
        instructor: "Martin Perhiniak",
        avg: 4.6,
        rating: "10,022",
        price: 15.99,
    },
] */

/* const code = [
    {
        img: "https://i.ibb.co/TKjMrBM/player-1.png",
        Expert: "Expert in Web Development",
        instructor: "Mosh Hamedani",
        Experience: "5+ Years"
        
    },
    {
        img: "https://i.ibb.co/mth99hR/player-3.png",
        Expert: "Expert in Digital Marketing",
        instructor: "Course Envy",
        Experience: "3+ Years"
        
    },
    {
        img: "https://i.ibb.co/VS6bNDx/player-5.png",
        Expert: "Expert in Graphic Design",
        instructor: "Tim Buchalka",
        Experience: "2+ Years"
        
    },
    {
        img: "https://i.ibb.co/646yVWV/player-4.png",
        Expert: "Expert in JavaScript",
        instructor: "Edwin Diaz",
        Experience: "4+ Years"
        
    },
    {
        img: "https://i.ibb.co/4tqPRS8/player-2.png",
        Expert: "Expert in PHP",
        instructor: "Martin Perhiniak",
        Experience: "6+ Years"
        
    },
    {
        img: "https://i.ibb.co/2ttQYGp/player-6.png",
        Expert: "Expert in C++",
        instructor: "Abdul Bari",
        Experience: "5+ Years"
        
    },
] */